import { sdgData } from './sdgData';

export const initialProjectsData = [
  {
    id: '1',
    nombre: 'EcoTech Solutions',
    creador: 'Ana García',
    fase: 'Semilla',
    sector: 'Sostenibilidad',
    region: 'Málaga',
    descripcion: 'Plataforma de gestión de residuos inteligente usando IoT para optimizar rutas de recogida y reciclaje.',
    ia: 'EcoBot - Asistente de optimización ambiental',
    agentes: ['Sensor de residuos', 'Predictor de rutas'],
    mentor: 'José Luis Nieto',
    impacto: '50,000 personas',
    documentos: ['Pitch Deck', 'Prototipo'],
    logo: null,
    fechaCreacion: new Date(2025, 0, 15).toISOString(),
    financiacionCaptada: 75000,
    valorEstimado: 300000,
    beneficioEstimadoMentor: 5000,
    lastFundingDate: new Date(2025, 0, 15).toISOString(),
    expectedMonthlyRevenue: 0,
    currentMonthlyRevenue: 0,
    progressStatus: 'on_track', 
    mentorInteractions: 5,
    entrepreneurParticipationLevel: 'alta',
    alerts: [],
    // Nuevos campos sociales
    project_kind: 'startup',
    sdgs: [sdgData[10], sdgData[11], sdgData[12]],
    impact_theory: 'Mediante la optimización de la recogida de residuos, reducimos la huella de carbono de los municipios y aumentamos las tasas de reciclaje, contribuyendo a ciudades más limpias y sostenibles.',
    beneficiaries_estimated: 50000,
    beneficiaries_served: 1200,
    impact_kpis: [
      { name: 'Reducción de emisiones CO2', target: '15%', current: '3%', unit: '%' },
      { name: 'Aumento de tasa de reciclaje', target: '20%', current: '5%', unit: '%' }
    ],
    trace_events: [],
    consent_social_share: true,
  },
  {
    id: '2',
    nombre: 'HealthAI Diagnostics',
    creador: 'Dr. Carlos Ruiz',
    fase: 'Pegaso',
    sector: 'Salud',
    region: 'Madrid',
    descripcion: 'IA para diagnóstico médico temprano de enfermedades raras a partir de imágenes médicas.',
    ia: 'MediBot - Asistente de diagnóstico',
    agentes: ['Analizador de imágenes', 'Predictor de riesgos'],
    mentor: 'José Luis Nieto',
    impacto: '100,000 pacientes',
    documentos: ['Business Plan', 'Estudios clínicos'],
    logo: null,
    fechaCreacion: new Date(2024, 5, 10).toISOString(),
    financiacionCaptada: 4000000,
    valorEstimado: 10000000,
    beneficioEstimadoMentor: 80000,
    lastFundingDate: new Date(2024, 8, 1).toISOString(),
    expectedMonthlyRevenue: 50000,
    currentMonthlyRevenue: 35000,
    progressStatus: 'needs_attention',
    mentorInteractions: 12,
    entrepreneurParticipationLevel: 'media',
    alerts: [
      { id: 'alert1', type: 'warning', message: 'Facturación un 30% por debajo de lo esperado.', date: new Date(2025, 4, 1).toISOString() },
    ],
    project_kind: 'startup',
    sdgs: [sdgData[2]],
    impact_theory: 'Al acelerar el diagnóstico de enfermedades raras, mejoramos la calidad de vida de los pacientes y reducimos los costes a largo plazo para los sistemas de salud.',
    beneficiaries_estimated: 100000,
    beneficiaries_served: 2500,
    impact_kpis: [
      { name: 'Tiempo de diagnóstico reducido', target: '50%', current: '25%', unit: '%' },
    ],
    trace_events: [],
    consent_social_share: false,
  },
  {
    id: '3',
    nombre: 'Agua para el Sahel',
    creador: 'Fatimah Al-Jamil',
    fase: 'Semilla',
    sector: 'Acción Humanitaria',
    region: 'Global',
    descripcion: 'Iniciativa para instalar y mantener pozos de agua potable en comunidades rurales del Sahel.',
    ia: 'WaterFlow AI',
    agentes: ['Monitor de nivel de acuíferos', 'Planificador de mantenimiento'],
    mentor: 'José Luis Nieto',
    impacto: '10,000 personas',
    documentos: ['Propuesta de proyecto', 'Estudio de viabilidad'],
    logo: null,
    fechaCreacion: new Date(2025, 2, 20).toISOString(),
    financiacionCaptada: 25000,
    valorEstimado: 0,
    beneficioEstimadoMentor: 0,
    lastFundingDate: new Date(2025, 2, 20).toISOString(),
    expectedMonthlyRevenue: 0,
    currentMonthlyRevenue: 0,
    progressStatus: 'on_track',
    mentorInteractions: 8,
    entrepreneurParticipationLevel: 'alta',
    alerts: [],
    project_kind: 'ong',
    sdgs: [sdgData[5], sdgData[0]],
    impact_theory: 'Proporcionar acceso a agua potable segura reduce las enfermedades transmitidas por el agua y libera tiempo para mujeres y niños, quienes tradicionalmente se encargan de su recolección, permitiendo la asistencia a la escuela y el desarrollo económico local.',
    beneficiaries_estimated: 10000,
    beneficiaries_served: 500,
    impact_kpis: [
      { name: 'Nuevos pozos funcionales', target: 20, current: 2, unit: 'unidades' },
      { name: 'Tasa de enfermedades hídricas', target: '-80%', current: '-10%', unit: '%' },
      { name: 'Horas diarias ahorradas por familia', target: 4, current: 1, unit: 'horas' },
    ],
    trace_events: [],
    consent_social_share: true,
  },
   {
    id: '4',
    nombre: 'Refugio Digital',
    creador: 'Marco Vega',
    fase: 'Pegaso',
    sector: 'Derechos Humanos',
    region: 'Global',
    descripcion: 'Plataforma segura para que periodistas y activistas en zonas de conflicto puedan archivar y compartir información de forma anónima y segura.',
    ia: 'Sentinel AI',
    agentes: ['Verificador de metadatos', 'Encriptador de datos'],
    mentor: 'José Luis Nieto',
    impacto: '500 activistas',
    documentos: ['Protocolo de seguridad', 'Análisis de riesgos'],
    logo: null,
    fechaCreacion: new Date(2024, 9, 1).toISOString(),
    financiacionCaptada: 150000,
    valorEstimado: 0,
    beneficioEstimadoMentor: 0,
    lastFundingDate: new Date(2024, 9, 1).toISOString(),
    expectedMonthlyRevenue: 0,
    currentMonthlyRevenue: 0,
    progressStatus: 'needs_attention',
    mentorInteractions: 15,
    entrepreneurParticipationLevel: 'media',
    alerts: [
      { id: 'alert-rd-1', type: 'warning', message: 'Se necesita actualizar el protocolo de encriptación.', date: new Date().toISOString() },
    ],
    project_kind: 'proyecto_social',
    sdgs: [sdgData[15]],
    impact_theory: 'Al proteger la información y la identidad de los activistas, fortalecemos la libertad de prensa y la defensa de los derechos humanos en las regiones más peligrosas del mundo.',
    beneficiaries_estimated: 500,
    beneficiaries_served: 45,
    impact_kpis: [
      { name: 'Número de usuarios activos', target: 500, current: 45, unit: 'usuarios' },
      { name: 'Intentos de ataque bloqueados', target: 1000, current: 150, unit: 'ataques' },
    ],
    trace_events: [],
    consent_social_share: false,
  }
];